version: "3.8"

services:
  datasette:
    restart: always
    image: datasetteproject/datasette
    env_file:
      - .env
    volumes:
      - ./data:/mnt/data
    ports:
      - "8001:8001"
    command: >
      datasette 
      -i /mnt/data 
      --inspect-file=/mnt/data/counts.json 
      --host 0.0.0.0 
      --port 8001 
      --setting max_returned_rows 100000 
      --setting sql_time_limit_ms 50000 
      --setting facet_time_limit_ms 50000 
      --setting max_csv_mb 0 
      --setting force_https_urls 1 
      --load-extension=spatialite

  datasette-inspect:
    image: datasetteproject/datasette
    volumes:
      - ./data:/mnt/data
    entrypoint: [
      "datasette", "inspect", 
      "/mnt/data", 
      "--inspect-file=/mnt/data/counts.json"
    ]
